### ISSUE TITLE
Potential issue in Annotations

### ISSUE THREAD

**Issue by kmkumaran** [Azure/k8s-deploy#112]
The k8s-deploy would annotate details required for traceability. This is a two step process

1. Deployment to resource
2. Annotate to resource - Which overwrites any existing annotations on the resource.

Since the steps are not transaction, parallel deployments to same resource can lead race conditions, with second annotation winning which need not be the same that is deployed.

**Comment by kmkumaran** [comment]
@ajinkya599 , @ds-ms - This came up in a review. Is there a way we can make annotation as part of deployment itself?

**Comment by ds-ms** [comment]
Yes it can done.

**Comment by ammohant** [comment]
@kmkumaran - yes, annotations can  be added/patched to the yaml itself.

**Comment by kmkumaran** [comment]
@ammohant , when is this fix planned?

**Comment by ds-ms** [comment]
@kmkumaran the fix for this would require us to revamp our core logic for image substitution and annotations. I'd say we'll wait until it's a valid scenario may be? 

FYI: This logic has been in Production in both ADO and Actions for about 2 years now, there weren't any customer reported issues on this front.

**Comment by koushdey** [comment]
This logic has been present for quite some time and have not seen any issue reported around it. Closing it for now until we encounter any issues reported for this.
