### ISSUE TITLE
Bug: Labeling resources multiple times

### ISSUE THREAD

**Issue by richardsimko** [Azure/k8s-deploy#264]
### What happened?

The latest version (4.7) is trying to label all resources multiple times. I believe the issue is with this loop which was introduced in #255: https://github.com/Azure/k8s-deploy/blob/b9a9965750c9d436e6136fcf42a3566508673fd1/src/strategyHelpers/deploymentHelper.ts#L259-L266

Each call labels all resources yet it makes one call for each file. This means that for a large deployment (We have about 20 manifests being deployed at once) it takes unreasonably long to deploy as it's repeating the same action over and over again. For our deployment it takes about 3 minutes to run on 4.7 and 17 seconds on 4.6.

I'm happy to fix the issue but I want to get some context as to why the loop was added in the first place as I don't want to break some other part of the workflow.

### Version

- [X] I am using the latest version

### Runner

github hosted

### Relevant log output

On 4.6 there is only a single line of:

```
  /usr/local/bin/kubectl label -f [all manifests being deployed] workflowFriendlyName=deploy workflow=actions.github.com-k8s-deploy --overwrite --insecure-skip-tls-verify
```

But on 4.7 it's repeating that line once for each file.

**Comment by jaiveerk** [comment]
Hi Richard,
Thanks so much for catching this! I believe the solution here is just to call labelResources on `file` instead of `files`. 

We use a loop in this case so that if annotations fail on a single file (or the objects in it), the action proceeds and still applies annotations to every other file passed to it. 

This should be a quick fix so we'll try to get a PR out for this soon.

Thanks again for the catch!

**Comment by richardsimko** [comment]
Thanks for the swift fix!
